all:
    # install pycocotools locally
	python3.8 setup.py build_ext --inplace
	rm -rf build

install:
	# install pycocotools to the Python site-packages
	python3.8 setup.py build_ext install
	rm -rf build